### PR TITLE
Support deeply nested includes

### PR DESCRIPTION
**Pull request by leo-naeka**
As reported in #200, include paths can be compound of many nodes.
When requesting a deeply nested node, all intermediate nodes must be included as well.

This PR is similar to #200 but involves less code base modifications and includes tests.

### CODE REVIEW

**Comment by adaptivdesign** [comment]
Looks great if you ask me, skips me the hassle of writing tests ;) I will cancel mine!

**Comment by leo-naeka** [comment]
@adaptivdesign Of course you're part of the discussion. I'm pleased you found this great as well.

**Comment by adaptivdesign** [comment]
Credit where credit is due! I see you've implemented polymorphic support as well, I'll have to check that out. Although i'm using an own implementation (django-polymorphism). That is why I needed nested inclusions in the first place, so I could query polymorphic endpoints/relations like this:

/projects?include=artproject&include=researchproject
/author?include=projects.artproject&include=projects.researchproject

**Comment by jerel** [comment]
@leo-naeka @adaptivdesign thank you both for your work on this.

**Pull request merged**
