### PR TITLE
Release 4.2.0

### LINKED ISSUE #911: Release needed for Django 3.2 Update
Hello,

I see that there was a change to allow Django 3.2, but no new release has happened. This is preventing us from upgrading, could we get a new version released?

Thank you!

### PR DESCRIPTION
**Pull request by sliverc**
Fixes #911 

## Description of the Change

Prepare release 4.2.0

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [ ] documentation updated
- [x] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

### CODE REVIEW

**Review by auvipy — APPROVED** [review]

**Comment by simkimsia** [comment]
Who can approve/merge this? I am eager to see if this allows me to upgrade to django 3.2...

**Comment by sliverc** [comment]
@n2ygk Rebased to master. Hope this direct message will be noticeable in your sea of notifications... :smile: It would be great to get this released soon.

**Comment by simkimsia** [comment]
Apologies about the recurring messages. 

I'm just checking in every Tuesday as scheduled on my calendar 'cause I have an upgrade where the blocker is just DJA and its compatibility with Django 3.2

**Comment by sliverc** [comment]
@n2ygk I do not know when I will find time again to release this and I think it would be good to do this rather early than later. So I force merge this now. Please comment though if there this is anything. And I hope you will find some time to look at the other PRs too which are still open. Thanks.

**Pull request merged**
