### PR TITLE
Revert "Fix the inclusion of relations"

### PR DESCRIPTION
**Pull request by jsenecal**
Reverts django-json-api/django-rest-framework-json-api#127

This broke many things using the include parameter.

@schtibe could you please document your issue in a proper 'issue' so that we can work on this ?

### CODE REVIEW

**Comment by schtibe** [comment]
See issue #131

**Comment by schtibe** [comment]
@jsenecal Can you tell me what broke because of this commit?

**Comment by jsenecal** [comment]
Infinite recursion on models with self relations. It also broke something for @jerel (please help me there @jerel)

**Comment by schtibe** [comment]
Ok... tried to reproduce with a model with self relation that I have, but couldn't. Am I doing it unlike you?
My Code:

```python
class Section(models.Model):
    parent_section = models.ForeignKey('Section', null=True, blank=True)
    name           = models.CharField(max_length=200, unique=True)
    code           = models.CharField(max_length=2, unique=True)
    slot_count     = models.IntegerField(default=6)

    def __str__(self):
        return self.name


class SectionSerializer(serializers.ModelSerializer):
    class Meta:
        model  = models.Section
        fields = ('id', 'parent_section', 'name', 'code')

SectionSerializer.included_serializers = {
        'parent_section': SectionSerializer
    }
```

Fixtures:
```json
  {
    "pk": 1,
    "model": "masterdata.Section",
    "fields": {
      "parent_section": null,
      "name": "foo",
      "name_de": "foo",
      "name_fr": "fuu",
      "code": "fo"
    }
  },
  {
    "pk": 2,
    "model": "masterdata.Section",
    "fields": {
      "parent_section": 1,
      "name": "bar",
      "name_de": "bar",
      "name_fr": "brr",
      "code": "ba"
    }
  },
```

The result:
```json
{"data": {"attributes": {"code": "ba", "name": "bar"},
          "id": "2",
          "relationships": {"parent-section": {"data": {"id": "1",
                                                        "type": "sections"}}},
          "type": "sections"},
 "included": [{"attributes": {"code": "fo", "name": "foo"},
               "id": "1",
               "relationships": {"parent-section": {"data": None}},
               "type": "sections"}]}

```

**Comment by jsenecal** [comment]
Well, my models are a bit more complicated than that and the actual issue might be related to issue #126 - To be quite honest I the issue appeared after merging your PR - I reverted it to test and the problem was gone - I did not investigate further - sry

I'm a bit swamped in a work-related project but I would like to write tests to help with the compound-documents feature. Let me know if you would like to help with those (it would be greatly appreciated)

**Comment by jerel** [comment]
The issue I was having wasn't a `self` relationship. The bug showed up as an undefined serializer class. I will likely have time today to write tests for this issue so we can resolve it properly

**Comment by jsenecal** [comment]
Oh yeah ! I remember now - yeah - the extract_included was stripping off included_serializers that shouldn't have been removed.

**Pull request merged**
