### PR TITLE
Split requirements files up following DRF example

### LINKED ISSUE #635: Tox using pytest-runner setup scripts leads to invalid deps
Currently tox uses pytest-runner setup script wrapper. This way tests are run differently when run locally as stated in README.md.

This may lead to different dependencies and errors as for example #634

Best to split up requirements as in [DRF](https://github.com/encode/django-rest-framework/tree/master/requirements) and remove setup pytest-runner script. Once this is done `test_requires` in setup.py would not be needed which remoes the duplication to requirements-development.txt

### LINKED ISSUE #712: Test sphinx docs build in test
To avoid invalid format in documentation sphinx warnings should be turned into warnings and sphinx docs build run in Travis.

This way it is also safer to update sphinx releases as when it passes it should be OK.

### PR DESCRIPTION
**Pull request by sliverc**
Fixes #712
Fixes #635 

## Description of the Change

This way not all dependencies need to be installed for the different testing steps.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [x] documentation updated
- [ ] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by sliverc** [comment]
@n2ygk 
This PR is just a start but requirements can been cleaned up even more when following issue are worked on.

#721 
#468 

However this is a start. Once this is merged I would like to release DJA 3.0 what do you think?

**Comment by n2ygk** [comment]
@sliverc Can you figure out why the sphinx build is failing? I've been staring at it and don't see why it shoud.

**Comment by sliverc** [comment]
@n2ygk 
I don't get it either. Although when I delete the `.tox/docs` and `docs/apidoc` folder locally I can reproduce the error when running tox -e docs, I don't quite understand though why.

**Comment by sliverc** [comment]
@n2ygk I think I have found it. Seems to be a regression of #711 Hope CI will pass now.

**Pull request merged**
