### PR TITLE
Use JSONAPIMeta in models to determine the resource name

### PR DESCRIPTION
**Pull request by jerel**
Replaces #152

### CODE REVIEW

**Comment by scottfisk** [comment]
Ill try to take a look at the merge conflicts today.

**Comment by scottfisk** [comment]
@jerel resolved the conflicts, squashed a few commits, and added missing docs.

**Comment by jerel** [comment]
@scottfisk thanks so much! Sorry for the lengthy merge accept that we've put you through :)

**Comment by jerel** [comment]
I'll merge as soon as Travis gets done running the tests

**Pull request merged**
