### PR TITLE
Feature to format the relation names

### PR DESCRIPTION
**Pull request by schtibe**
Implemented a new option to be able to format the key names in
relations.

### CODE REVIEW

**Comment by jsenecal** [comment]
Why was this closed?

**Comment by schtibe** [comment]
I messed up my repo. Here it is again.

**Comment by jerel** [comment]
I just have two points of feedback:

1. Would it make sense to move `inflector.pluralize()` inside of `format_relation_name` so it's not repeated everywhere?
2. Add a note to [this file in the docs](/django-json-api/django-rest-framework-json-api/blob/develop/docs/usage.md) that the option exists

**Comment by schtibe** [comment]
@jerel I guess that would make sense, I changed it.

**Comment by jerel** [comment]
Good work, thanks for this!

**Pull request merged**
