### PR TITLE
added a factory with relations and some basic tests

### PR DESCRIPTION
**Pull request by abdulhaq-e**

### CODE REVIEW

**Comment by abdulhaq-e** [comment]
A PR apparently used code which only works on Django 1.8. I'll try to investigate.

**Comment by jsenecal** [comment]
I fixed  that in  #97 but I am still working on it.

On Sep 18, 2015 6:05 PM, Abdulhaq Emhemmed <notifications@github.com> wrote:

A PR apparently used code which only works on Django 1.8. I'll try to investigate.

**Comment by abdulhaq-e** [comment]
Great, you might find [this](https://docs.djangoproject.com/en/1.8/releases/1.8/#model-attribute-on-private-model-relations) section from Django 1.8 release notes useful.

**Comment by jsenecal** [comment]
Sure, I stumbled across these already.

**Comment by jerel** [comment]
@abdulhaq-e thanks for this, I merged it to the `develop` branch

**Pull request closed without merging**
