### PR TITLE
test on Python 3.5

### PR DESCRIPTION
**Pull request by jamesturk**
* required bumping the pytest version, doesn't seem to cause any issues
* tox base python set to 3.5 so it's available for tox

(tests are getting long, probably OK to drop Python 3.2 support, maybe 3.3 as well?)

### CODE REVIEW

**Comment by jamesturk** [comment]
(also realized it might be OK to drop Django 1.6 support as security updates ended in April)

**Comment by jsenecal** [comment]
I think that contains code from #134 right ?

**Comment by jamesturk** [comment]
yep, this is a superset of #134

**Comment by jerel** [comment]
Thanks for this! Excellent work.

**Pull request merged**
