### PR TITLE
Add DRF 3.7 and Django 2.0 to the test matrix.

### LINKED ISSUE #388: Add support for Django REST Framework 3.7 and Django 2.0
DJA should be tested against DRF 3.7.x and document that support.

### PR DESCRIPTION
**Pull request by mblayman**
Fixes #388

### CODE REVIEW

**Comment by mblayman** [comment]
The DJA test suite relies on the example app which, in turn, relies on django-polymorphic. There is an open issue with django-polymorphic (https://github.com/django-polymorphic/django-polymorphic/issues/324) that prevents it from running on Django 2.0.

Once django-polymorphic works on Django 2.0, I can come back to this branch and (hopefully), merge it.

**Comment by sliverc** [comment]
Maybe we should think about making the dependency django-polymorphic optional as the majority of  users are properly not using it. So if someone wants to use it they already have the dependency set in their own project to create the models and DJA will detect it that it is installed.

This way DJA wouldn't be blocked by issues like this to upgrade to a newer Django and DRF version. The tests in this PR would simply need to exclude polymorphic tests to be run on Django 2.0 till django-polymorphic has fixed it.

**Comment by mblayman** [comment]
I considered that route, but ultimately decided against it because I thought it would be too confusing.

If DJA released a version compatible with Django 2.0, but didn't work with django-polymorphic because polymorphic still doesn't work with 2.0, then I feel like the documentation would be lying to users. I'm not comfortable stating DJA supports Django 2.0 and django-polymorphic at the same time.

In addition (and probably the bigger problem), the example app uses a polymorphic model, and I don't know how to conditionally make models in the example app in a way that won't cause migrations oddities. One part of this project that I find puzzling is that the entire test suite is extremely coupled to the example project. I understand that it's for historical reasons, but I think that is the blocker.

I think that the 2.0 branch for polymorphic is blocked (https://github.com/django-polymorphic/django-polymorphic/pull/318) so maybe the best thing we could do is go help them get unblocked. 😄

**Comment by sliverc** [comment]
Fair enough. Not sure whether I will find the time myself but it would properly be a good idea to assist django-polymorphic with 2.0 support.

**Comment by mblayman** [comment]
Cool, it looks like there was progress on the django-polymorphic issue. I'll keep my eyes open for a new release that has support for Django 2.0.

**Comment by mblayman** [comment]
Excellent! Many folks are looking for a Django 2.0 compatible release so I'm going to merge this and make a release in the next couple of days.

**Comment by dbinetti** [comment]
Hey @mblayman thanks for your efforts here.  Any chance you could cut a release?

**Comment by dbinetti** [comment]
Ooops! I checked 'latest' but didn't look deeply enough.  Apologies @mblayman  for the interruption....  deleting comment.

**Pull request merged**
