### PR TITLE
Drop support for obsolete dependencies

### LINKED ISSUE #658: python 3.4 deprecated
Python 3.4 is dropped by upstream DRF per https://github.com/encode/django-rest-framework/pull/6620

We should drop it from DJA as well.

```
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting https://github.com/encode/django-rest-framework/archive/master.zip
  Downloading https://github.com/encode/django-rest-framework/archive/master.zip
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: 
    ==========================
    Unsupported Python version
    ==========================
    
    This version of Django REST Framework requires Python 3.5, but you're trying
    to install it on Python 3.4.
    
    This may be because you are using a version of pip that doesn't
    understand the python_requires classifier. Make sure you
    have pip >= 9.0 and setuptools >= 24.2, then try again:
    
        $ python -m pip install --upgrade pip setuptools
        $ python -m pip install djangorestframework
    
    This will install the latest version of Django REST Framework which works on
    your version of Python. If you can't upgrade your pip (or Python), request
    an older version of Django REST Framework:
    
        $ python -m pip install "django<3.10"
    ----------------------------------------

```

### PR DESCRIPTION
**Pull request by sliverc**
Fixes #658
Fixes #659  

## Description of the Change

Following specific supports are removed:
* Python 2.7
* Python 3.4
* Django Filter 1.1
* Django REST Framework >=3.8
* Django 2.0

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [x] documentation updated
- [ ] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by sliverc** [comment]
@n2ygk currently work in progress and should only be merged once #663 has been released.

One missing step is to get rid of `six` dependencies.

**Comment by sliverc** [comment]
Removing six was easier than anticipated. I hope all obsolete workarounds for Python 2.7 are now removed.

I will do removing of deprecated code in another PR.

**Comment by n2ygk** [comment]
@sliverc I believe you need to tag this "Ready for review" since it's still labeled as a draft....

**Comment by sliverc** [comment]
@n2ygk Added changelog and found another Py27 code snippet to be removed. Ready for final review now.

**Pull request merged**
