### PR TITLE
Release 2.5.0

### PR DESCRIPTION
**Pull request by sliverc**
It's time again for another release as quite a few important fixes/changes have been added.

@mblayman 
This will be the first release I will make. You have already documented concerning twine. I assume I do not have pypi rights for this project yet though?
Also another question how do we update Read The Docs?

Thanks for your feedback.

### CODE REVIEW

**Comment by sliverc** [comment]
@mblayman My user name on PyPI is `sao`.

**Comment by mblayman** [comment]
Looks like I don't have permission to add you as a maintainer.

image

@jerel, can you give us a hand by adding a `sao` as a maintainer to DJA on PyPI?

**Comment by jerel** [comment]
done

**Comment by sliverc** [comment]
Thanks @jerel in terms of Read The Docs it seems that `latest` is still linked to `develop` branch. Could you change this to `master` branch? I do not seem to have access to edit it.

**Comment by jerel** [comment]
also done, let me know if either of you have a ReadTheDocs account and I'll add you

**Comment by sliverc** [comment]
Thanks @jerel  My read the docs account is `sliverc`

**Pull request merged**
