### PR TITLE
blog app

### PR DESCRIPTION
**Pull request by abdulhaq-e**
This is a basic blog app that can be used for testing. I wasn't sure about the best git workflow, I needed to use PR https://github.com/django-json-api/django-rest-framework-json-api/pull/71 so it's included in this PR.

The blog fixtures will be extended as I add more tests. these tests should complete the last task in 2.0 milestone.

### CODE REVIEW

**Comment by jerel** [comment]
Thanks for this, we'll try to get it reviewed shortly

**Comment by jsenecal** [comment]
@jerel - Seems good to me, thanks @abdulhaq-e! We should merge this into its own feature branch for now though...

**Comment by abdulhaq-e** [comment]
Anything new with this PR?

I'll be adding new tests and I'm confused with all the bug fixes that were added. If this can be merged somewhere I will add the tests.

Thanks

**Comment by jsenecal** [comment]
Yes, actually we were going to start on this tomorrow morning - Will you be reachable on gitter?

**Comment by abdulhaq-e** [comment]
At what time?

**Pull request merged**
