### PR TITLE
Extract type for each related instance

### PR DESCRIPTION
**Pull request by martinmaillard**
Instead of extracting the resource type for the whole related collection, extract the type for each instance individually. This way, polymorphic relationships (using something like django_polymorphic) are
supported.

This PR addresses an issue raised in https://github.com/django-json-api/django-rest-framework-json-api/issues/77

The next step will be to allow customizing the way the type is extracted for each instance, but I'm not sure how to go about that...

### CODE REVIEW

**Comment by jsenecal** [comment]
Could you provide us with a way to replicate your issue and test your solution uppon it? I don't see any problem about it but I would like to make sure. 

Also, what/how exactly does that address #77 ?

**Comment by martinmaillard** [comment]
It addresses this comment https://github.com/django-json-api/django-rest-framework-json-api/issues/77#issuecomment-141083344

I'll try to write a test.

**Comment by jsenecal** [comment]
ha! okay I missed that comment - I have nothing against merging that... @jerel any objections ?

**Comment by jerel** [comment]
Once we get the `example` app set up properly we can require tests an a PR

**Comment by martinmaillard** [comment]
Was that reverted ?

**Comment by jerel** [comment]
I don't believe so:
https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/utils.py#L370

**Pull request merged**
