### PR TITLE
respect custom related_link_url_kwarg

### PR DESCRIPTION
**Pull request by ola-t**
fix https://github.com/django-json-api/django-rest-framework-json-api/issues/358

### CODE REVIEW

**Comment by mblayman** [comment]
Hi, @ola-t! Thanks for the contribution. The fix looks good to me. 👍

As this is a community run project, we'd like for every contributor to get credit for their work. Could you add your name to the AUTHORS file (it's alphabetical by first name)? I'm happy to merge the work after that.

**Comment by Darkheir** [comment]
This doesn't fix the problem in the many-many relations. 

The folowing line should also be corrected :
https://github.com/ola-t/django-rest-framework-json-api/blob/ef3e61f55e9a89b30e5c6147eeafe92145a82d27/rest_framework_json_api/renderers.py#L193

To be
```python
field_links = field.child_relation.get_links(resource_instance, field.child_relation.related_link_lookup_field)
```

**Comment by mblayman** [comment]
@Darkheir, thanks for thinking about that case. If you could make a separate pull request, that would probably be the quickest fix for the many-to-many issue. I'm going to go ahead and merge this one.

**Comment by ola-t** [comment]
When are you planning to release these bug fixes?

**Comment by mblayman** [comment]
I would like to see a release soon. I either need to get upload permission to PyPI to do it or @jerel will need to release the package. Either action will require some input from him that's out of my control.

Before the release, I think the demo site needs to be fixed so #356 is a blocker that should be addressed.

**Pull request merged**
