### PR TITLE
Added django 2.2 LTS support

### PR DESCRIPTION
**Pull request by auvipy**
work on progress

### CODE REVIEW

**Comment by auvipy** [comment]
should we drop python 2.7 support?

**Comment by auvipy** [comment]
@sliverc

**Comment by sliverc** [comment]
We support Python 2.7 as long as Django REST Framework does (of course only for the Django Version which support 2.7 as well).

In terms of this PR please keep it to adding test for Django 2.2 (there are other changes not relevant to Django 2.2 which also make CI fail).

Thanks for working on this.

**Comment by auvipy** [comment]
OK. I will modify this PR. drf is going to drop python 2.7 in 3.10 due to be released in next month. And I am working on the python2.7 dropping works there.

**Comment by sliverc** [comment]
I have worked on this in PR #640 

I guess once DRF 3.10 is released we will need to do another DJA release and then cleanup the testing matrix.

**Pull request closed without merging**
