### PR TITLE
Support tags in OAS schema

### LINKED ISSUE #910: Apply tags defined in OAS schema
In https://github.com/encode/django-rest-framework/pull/7184, tags support was added to DRF.
It can be viewed here:
https://github.com/encode/django-rest-framework/pull/7184/files#diff-99d3943485b50b323271fe5399dab8b2c778f42cbc0749b0f702e4cab0a81b2cR107

DJA doesn't yet have this added.

### PR DESCRIPTION
**Pull request by SafaAlfulaij**
Fixes #910

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [x] unit-test added
- [ ] documentation updated
- [x] `CHANGELOG.md` updated (only for user relevant changes)
- [ ] author name in `AUTHORS`

### CODE REVIEW

**Review by sliverc — APPROVED** [review]
This looks good to me. @n2ygk Could you have a look at this though? You have a better inside into openapi support and whether this support makes sense in the DJA context.

**Review by n2ygk — CHANGES_REQUESTED** [review]
I don't see documentation for how one would use this feature.  Please add that and include an example. Specifically, where is get_tags() defined and what happens if it's not defined?

**Comment by SafaAlfulaij** [comment]
> 
> 
> I don't see documentation for how one would use this feature. Please add that and include an example. Specifically, where is get_tags() defined and what happens if it's not defined?

It's using DRF AutoSchema: https://www.django-rest-framework.org/api-guide/schemas/#autoschema__init__-kwargs

```python
class PetDetailView(generics.RetrieveUpdateDestroyAPIView):
    schema = AutoSchema(
        tags=['Pets'],
        component_name='Pet',
        operation_id_base='Pet',
    )
    ...
```

**Comment by n2ygk** [comment]
> > I don't see documentation for how one would use this feature. Please add that and include an example. Specifically, where is get_tags() defined and what happens if it's not defined?
> 
> It's using DRF AutoSchema: https://www.django-rest-framework.org/api-guide/schemas/#autoschema__init__-kwargs
> 
> ```python
> class PetDetailView(generics.RetrieveUpdateDestroyAPIView):
>     schema = AutoSchema(
>         tags=['Pets'],
>         component_name='Pet',
>         operation_id_base='Pet',
>     )
>     ...
> ```

Aha! Sorry I missed that.  Please add yourself to AUTHORS and rebase this on current master. Thanks for your contribution!

**Comment by n2ygk** [comment]
@SafaAlfulaij thanks for this!

**Pull request merged**
