### PR TITLE
WIP: initial openapi schema generator implementation

### LINKED ISSUE #604: Support DRF 3.10+ generateschema (OAS 3)
DRF 3.10 is adding support to generate an openapi 3.0 schema: https://github.com/encode/django-rest-framework/pull/6532. There will likely be some enhancements needed for DJA to support this new functionality.

### PR DESCRIPTION
**Pull request by n2ygk**
Fixes #604 

## Description of the Change
Extends DRF >= 3.10's generateschema to produce a jsonapi-formatted OAS schema document.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [x] unit-test added
- [ ] documentation updated
- [ ] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

This is currently conditionalized to test for DRF >=3.10 so none of the test cases are executed, even with drfmaster (since 3.10 is not yet released), but, if you comment out those tests then it should work with drfmaster. Still some build failures with obsolete py27, py34, django111, etc. which should go away  when #664 is merged.

### CODE REVIEW

**Comment by n2ygk** [comment]
TODOs:
- [ ] improve test coverage
- [ ] add documentation
- [ ] submit 3rd party documentation to https://github.com/encode/django-rest-framework/pull/6668

**Comment by sliverc** [comment]
This is quite a lengthy PR so not sure when I will find time to look at it. But I assume you are still working on it?

As this is another optional feature we should fix #674 first to cleanly define optional deps needed by this feature.

**Comment by arielpontes** [comment]
Any news about this? I see the only missing checks are:

1. updating docs
2. updating CHANGELOG.md

Anything I could perhaps help with?

**Comment by n2ygk** [comment]
> Any news about this? I see the only missing checks are:
> 
> 1. updating docs
> 2. updating CHANGELOG.md
> 
> Anything I could perhaps help with?

@arielpontes Thanks for the offer to help.

There's a bit more to do than that, including the [TODOs](https://github.com/django-json-api/django-rest-framework-json-api/pull/669#issuecomment-507281715) referenced above and the need to do #674 first. Perhaps you can start on that? There's also an additional optional package which is django-oauth-toolkit (used in generateschema to add oauth `securitySchemes` and `security` objects for path methods) which would I think also need to get added to the optional packages.

This code is based on DRF 3.10 pre-release which has since had a [couple of minor releases](https://pypi.org/project/djangorestframework/#history) -- currently at 3.10.2 -- so there may be some additional changes needed. I wanted to wait until DRF 3.10 settled down a bit and hope to have some time in the next week or two to get back to this, so it would really help if you (or @sliverc) could knock out #374.

Thanks!

**Comment by n2ygk** [comment]
I'm closing this in lieu of a new PR that isn't all messed up with the various merges from master.

**Pull request closed without merging**
