### PR TITLE
Include metadata in JSONParser output

### PR DESCRIPTION
**Pull request by hamedahmadi**
The JSONParser will add metadata in the request under a top level key `_meta`.

This provides access to the data in the `meta` tag of the request.

### CODE REVIEW

**Comment by jerel** [comment]
@hamedahmadi this looks like a nice addition. What is the reason for choosing `_meta` as the key name rather than `meta`?

**Comment by hamedahmadi** [comment]
@jerel using `_meta` to prevent a clash in case the resource has a `meta` attribute.

**Comment by jerel** [comment]
@hamedahmadi ok, makes sense. Would you mind adding some simple documentation yet before I merge? Make a note about parsing incoming meta here: [docs/usage.md#meta](/django-json-api/django-rest-framework-json-api/blob/develop/docs/usage.md#meta) and add a section for `JSONParser` here with `parse_metadata` documented: [docs/api.md](/django-json-api/django-rest-framework-json-api/blob/develop/docs/api.md)

**Comment by hamedahmadi** [comment]
@jerel Thanks for the comment, updated.

**Pull request merged**
