### PR TITLE
django >=2.2, <=3.1 (drops 1.11)

### LINKED ISSUE #822: add Django 3.1
[Django 3.1](https://docs.djangoproject.com/en/3.1/releases/3.1/) is recently released. Upstream DRF has passing tests for it but has not yet published support for it.

### PR DESCRIPTION
**Pull request by n2ygk**
Fixes #822, #803

## Description of the Change

Remove Django 1.11 from and add Django 3.1 to test matrix, setup.py

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [ ] documentation updated
- [x] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by n2ygk** [comment]
ugh, forgot that .travis.yml separately lists the environents.

**Comment by sliverc** [comment]
Thanks for looking out for this. I think we should wait with this PR though as DRF 3.11 is not officially supporting Django 3.1. Also locally on my machine the tests are failing with DRF 3.11 and Django 3.1. Reason seems that the `setup.py` is not updated yet in terms of Django range and Travis actually doesn't install Django 3.1 but still 3.0.

See for example [this job](https://travis-ci.org/github/django-json-api/django-rest-framework-json-api/jobs/723871737)

**Comment by n2ygk** [comment]
OK, I've updated setup.py to add py38, and django<3.2. Let's see if that at least fixes the travis job.

**Comment by n2ygk** [comment]
@sliverc FYI - I've opened https://github.com/encode/django-rest-framework/issues/7518 as it does appear that Django 3.1 is supported as of DRF 3.11.1 but the documentation is lagging.

**Comment by sliverc** [comment]
It was quicker to create a new PR #835 instead of updating this. Superseded therefore.

**Pull request closed without merging**
