### PR TITLE
Clean up python2 related code crafts

### PR DESCRIPTION
**Pull request by auvipy**
Fixes #

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [ ] documentation updated
- [ ] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

### CODE REVIEW

**Review by sliverc — CHANGES_REQUESTED** [review]
Thanks for this clean up task. Really appreciated. Could you please run `black .` and push again? Then it will be ready for merging.

**Comment by auvipy** [comment]
OK sure

**Comment by auvipy** [comment]
pushed new changes

**Review by sliverc — APPROVED** [review]
Thanks for your contribution. LGTM.

**Comment by auvipy** [comment]
would be happy to help. thanks for this cool project.

**Pull request merged**
