### PR TITLE
support polymorphic list with proper type/fields resolution

### PR DESCRIPTION
**Pull request by robertobarreda**
Render polymorphic list of items with different fields/type

### CODE REVIEW

**Comment by mblayman** [comment]
Hi @robertobarreda. Thanks for the contribution. The project's policy is to only merge work that passes all continuous integration tests. If you're still interested in this branch, could you make sure that CI is passing. I'm happy to review once that check is out of the way. If that's not something you have time for, then we can close out the PR.

**Comment by mblayman** [comment]
Ah, it looks like CI might actually be failing because of a factory boy dependency problem. Once #373 is merged, you can probably merge develop into your branch to fix CI.

**Comment by mblayman** [comment]
hi @robertobarreda, it looks like this might be close to ready. I think if you merge the `develop` branch into this, the branch will get the necessary package update to make the CI build work.

**Comment by robertobarreda** [comment]
Sorry @mblayman, I merged the develop branch but CI is still failing :(

**Comment by mblayman** [comment]
Looks like there are a couple of issues:
1. The branch has a flake8 error which needs to be fixed.
2. There's an import problem. I did a Google search on the exception and found another issues from *this* repository that's similar. https://github.com/django-json-api/django-rest-framework-json-api/issues/158 My best guess is that there is some kind of circular import error. Maybe, instead of importing PolymorphicModelSerializer directly, you can import `serializers` and access the model serializer like `serializers.PolymorphicModelSerializer`.

Thanks for your diligence in working on this. I'm sure that users who use the polymorphic features will be grateful.

**Comment by adsized** [comment]
Just found this pull request and realised that it would probably solve the issue #400 I raised as well as perhaps help with issue #401 which seemed similar.

I can see that some tests still seemed to be failing on some of the travis builds that are configured to use older versions of python. @robertobarreda @mblayman Do you know what was blocking getting this merged in?

**Comment by mblayman** [comment]
<snark>Travis CI</snark> 😉 To keep our sanity on the project, we only merge stuff that passes Travis builds. I suspect there is a problem with circular imports with this PR, but I'm not certain. If someone has time to check out the branch, figure the problem out, and get the branch updated to work in CI, I'd be happy to merge this.

**Comment by adsized** [comment]
@mblayman It makes perfect sense only merging stuff that passes the CI builds, I can perfectly understand that :smile:

I have checked out out the code from this pull request and had a look at where the errors are coming from. It does seems they were being caused by the serializers import in the renderers file.

From what I have read, the from x import y syntax requires a module to be completely initialized, whereas a simple import does not. By changing this, all of the tests now pass in my environment under both python2.7 and python3.6.

I'd be quite happy to commit my changes. Is there any easy way I can add a commit to this pull request or would I need to open a new one?

**Comment by mblayman** [comment]
@adsized, thanks for looking into this. I'd suggest putting up a separate PR. We'll make sure that both you and @robertobarreda get credit for the work and get those issues closed out. Please note that we're now working off of `master` instead of the old `develop` branch. I'm not sure if that will cause more work for you or not.

I look forward to seeing the Pull Request! 😄

**Comment by mblayman** [comment]
@adsized fixed the import issues in his PR. Thanks @robertobarreda!

**Pull request closed without merging**
