### PR TITLE
ResourceRelatedField now accepts serializer methods which return querysets.

### PR DESCRIPTION
**Pull request by rollokb**
Specifying the source of a field to be a method on a serializer, only works if `many=False`.  This pull request allows you to use serializer methods for `ResourceRelatedField` which return multiple objects.

Which allows you to do things like this:

    class EntrySerializer(serializers.ModelSerializer):
        included_serializers = {
            'approved_comments': 'example.serializers.EntrySerializer',
        }
        approved_comments = relations.ResourceRelatedField(source='get_approved_comments',
                many=True, model=Comment, read_only=True)

        def get_approved_comments(self, obj):
            return self.comments.approved()

### CODE REVIEW

**Comment by jsenecal** [comment]
@rollokb Please answer to @jerel 's questions/comments or we will otherwise have to close this PR.

Thanks :)

**Comment by rollokb** [comment]
@jerel sorry I just saw these in my email. I'll get back to you by the evening (UTC).

**Comment by jsenecal** [comment]
@rollokb any news on this ?

**Comment by cpa** [comment]
If the original author is fine with it, I'd like to take over this PR.

@jerel, which part of the PR are you referencing in this comment?
> The way our ResourceRelatedField was implemented before wasn't ideal (source was ambiguous between serializer and model) so this functionality has been moved to the more explicitly named SerializerMethodResourceRelatedField since you opened this PR.

Thanks!

**Comment by jerel** [comment]
@cpa the functionality should ideally be moved into `SerializerMethodResourceRelatedField` with `many=True` instead of adding `ManyResourceRelatedField` like this PR does.

**Pull request closed without merging**
