### PR TITLE
Serializermethod links

### PR DESCRIPTION
**Pull request by Anton-Shutik**
Added `self` and `related` links to `SerializerMethodResourceRelatedField`

### CODE REVIEW

**Comment by Anton-Shutik** [comment]
@jerel Any thought on that ? I find it very useful :)

**Comment by Anton-Shutik** [comment]
@jsenecal , @leifurhauks What are your thought on the PR ?

**Comment by jsenecal** [comment]
Hi @Anton-Shutik - @leifurhauks and I are a bit out of the loop on that project - sorry that we can't help further.

**Comment by chrisclark** [comment]
@jerel are you the right person to take a look at this?

Also, if some of the other guys are backing away from the project, would you be willing to add a couple of our folks (@Anton-Shutik, @noazark, me) as maintainers so we can review and merge PRs? We're very committed to this project and have a large production app using it (www.grove.co). @noazark has been using json-api even before the official spec was finished by Yehuda, and is involved in the ember community.

**Comment by jerel** [comment]
@chrisclark sure, I'm still using this project and mean to maintain it but I have a lot on my plate right now and would appreciate if others can dig in and keep it moving. It seems to be to a point where it has 90% of the features that everyone needs and 100% of what my current project needs so I'm often not scratching my own itch by merging a PR.

I've given several of you commit access.

**Comment by chrisclark** [comment]
Thanks @jerel. We've now been using this in production for a couple of weeks. That along with the test coverage @Anton-Shutik provided, gives me a lot of confidence to merge. Doing so now.

**Comment by jerel** [comment]
:+1:

**Pull request merged**
