### PR TITLE
Test to see how Travis is working.

### PR DESCRIPTION
**Pull request by mblayman**
Fixes #

## Description of the Change

This is to see if Travis is still triggered on new PRs.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [x] unit-test added
- [x] documentation updated
- [x] changelog entry added to `CHANGELOG.md`
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by mblayman** [comment]
@n2ygk It does look like a recent repo config change affected Travis. This test branch is not running either.

**Comment by mblayman** [comment]
It looks like it is still sitting there. What did we change recently about the repo setup? @jerel or @sliverc, do either of you know what has changed that might block Travis?

**Comment by n2ygk** [comment]
@mblayman wondering if you are seeing the notes I'm sending @gaker and @jerel in the maintainers list....

**Comment by n2ygk** [comment]
Thanks. I see @jerel added us as maintainers. The Travis integration is under @gaker's account. Should we try changing that? There's also a deprecation warning about integrations changing to webhooks.... I've not (yet) configured Travis so I'm probably not the best person to try this....

**Comment by n2ygk** [comment]
I'm clicking around the travis stuff some. It showed as not an active integration so I activated it.

**Comment by n2ygk** [comment]
I switched it to run under my profile because it seems to have cleared out @gaker's... Still messing with it.

**Comment by n2ygk** [comment]
That seems to have fixed it. #430 is building now. Please poke this one with a new commit to see if it also works.

**Comment by mblayman** [comment]
Ok, this branch did its job and proved that Travis is back so I'm closing it.

**Pull request closed without merging**
