### PR TITLE
Unified usage of JSON:API abbreviation

### LINKED ISSUE #940: Use JSON:API instead of JSON API
Recently there have been some confusion that DJA got confused with plain DRF like #930 and #894. I guess the naming of the JSON:API specification is not ideal :smile: 

It is though that in our readme and many other spots we use the term "JSON API" in the [json api spec](https://jsonapi.org/format/) "JSON:API" is used though.

So I suggest we find all "JSON API" references and replace it with "JSON:API". Hope this will reduce the confusion.

### PR DESCRIPTION
**Pull request by MsMansiDhruv**
Fixes #940

## Description of the Change
Update JSON: API from JSON API in the docs. 
Test the updated docs at [Read the JSON: API](https://django-rest-framework-json-api-modify.readthedocs.io/en/docs-update/)

### CODE REVIEW

**Review by sliverc — CHANGES_REQUESTED** [review]
Thanks a lot. Really appreciate you take a look at this!

Just a quick grep seems you missed just a few occurrences of `JSON API`:

```
CHANGELOG.md:* Added `rest_framework_json_api.serializer.Serializer` class to support initial JSON API views without models.
SECURITY.md:If you believe you've found something in Django REST Framework JSON API which has security implications, please **do not raise the issue in a public forum**.
requirements.txt:# The base set of requirements for Django REST framework JSON API is actually
rest_framework_json_api/exceptions.py:    # Use regular DRF format if not rendered by DRF JSON API and not uniform
rest_framework_json_api/exceptions.py:    # Convert to DRF JSON API error format
rest_framework_json_api/exceptions.py:    # Add top-level 'errors' object when not rendered by DRF JSON API
rest_framework_json_api/renderers.py:            # ID is always provided in the root of JSON API so remove it from attributes
rest_framework_json_api/settings.py:            raise AttributeError("Invalid JSON API setting: '%s'" % attr)
setup.py:    description="A Django REST framework API adapter for the JSON API spec.",
```

Could you update those as well? And please add yourself to the `AUTHORS` file too. Thanks.

**Comment by MsMansiDhruv** [comment]
> Thanks a lot. Really appreciate you take a look at this!
> 
> Just a quick grep seems you missed just a few occurrences of `JSON API`:
> 
> ```
> CHANGELOG.md:* Added `rest_framework_json_api.serializer.Serializer` class to support initial JSON API views without models.
> SECURITY.md:If you believe you've found something in Django REST Framework JSON API which has security implications, please **do not raise the issue in a public forum**.
> requirements.txt:# The base set of requirements for Django REST framework JSON API is actually
> rest_framework_json_api/exceptions.py:    # Use regular DRF format if not rendered by DRF JSON API and not uniform
> rest_framework_json_api/exceptions.py:    # Convert to DRF JSON API error format
> rest_framework_json_api/exceptions.py:    # Add top-level 'errors' object when not rendered by DRF JSON API
> rest_framework_json_api/renderers.py:            # ID is always provided in the root of JSON API so remove it from attributes
> rest_framework_json_api/settings.py:            raise AttributeError("Invalid JSON API setting: '%s'" % attr)
> setup.py:    description="A Django REST framework API adapter for the JSON API spec.",
> ```
> 
> Could you update those as well? And please add yourself to the `AUTHORS` file too. Thanks.

Sorry about the miss and the delay. Have updated accordingly. While updating I came across a term like "jsonapi". Wasn't sure if it needed to be updated to "json:api". Do let me know if I should modify it as well.

**Comment by sliverc** [comment]
Thanks. Yes `jsonapi` in text should also be renamed to `JSON:API` but I think it is mostly urls except one I saw in `test_filters.py`. Maybe you find more.

The upper case term `JSONAPI` is actually also used in comments (like openapi.py) which should also be `JSON:API`. Just need to be careful not to rename code bits like class `JSONAPIMetadata` where  a colon can of course not be used.

You have already changed some bits from "json api" to "json:api". Actually for consistency let's make sure that all occurrences are uppercase as "JSON:API".

This issue is actually trickier than I thought but it is great when we look at this with four eyes to make sure  the wording of "JSON:API" is used the same in the whole documentation and code comments.

**Comment by MsMansiDhruv** [comment]
> Thanks. Yes `jsonapi` in text should also be renamed to `JSON:API` but I think it is mostly urls except one I saw in `test_filters.py`. Maybe you find more.
> 
> The upper case term `JSONAPI` is actually also used in comments (like openapi.py) which should also be `JSON:API`. Just need to be careful not to rename code bits like class `JSONAPIMetadata` where a colon can of course not be used.

Alright, will modify it as well.


> You have already changed some bits from "json api" to "json:api". Actually for consistency let's make sure that all occurrences are uppercase as "JSON:API".

Sorry, I was under the impression that the case needs to be maintained. However, I shall update it to "JSON:API".

**Review by sliverc — APPROVED** [review]

**Comment by sliverc** [comment]
@MsMansiDhruv 
I have found some time to work on this. So the last occurrences should now also be renamed...

Thanks a lot for your initial work. One request I have though. Could please delete django-rest-framework-json-api-modify on [Read the docs](https://django-rest-framework-json-api-modify.readthedocs.io/en/docs-update/) which you created for testing? So users are not confused which one is now the official documentation. Thanks.

**Comment by MsMansiDhruv** [comment]
Sorry, I wasn't able to find time to fix this. I have deleted the link to the documentation.

**Pull request merged**
